# Generated by Django 5.0.4 on 2026-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolleyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('position', models.CharField(choices=[('setter', 'Setter'), ('outside_hitter', 'Outside Hitter'), ('opposite', 'Opposite Hitter'), ('middle_blocker', 'Middle Blocker'), ('libero', 'Libero'), ('defensive_specialist', 'Defensive Specialist')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
